services:
  fab:
    build:
      context: .
      args:
        - USE_DEV_REQUIREMENTS=true
    volumes:
      - .:/fab:cached
    command: sleep infinity
    environment:
      - DATABASE_URL=postgresql://postgres:password@fab-db:5432/fab
      - SECRET_KEY=local
      - FLASK_ENV=development


  fab-db:
    image: postgres@sha256:fe4efc6901dda0d952306fd962643d8022d7bb773ffe13fe8a21551b9276e50c
    environment:
     - POSTGRES_PASSWORD=password
