services:
  fab-dc:
    hostname: fab-dc
    container_name: fab-dc
    build:
      context: ../funding-service-design-fund-application-builder
      dockerfile: Dockerfile
      args:
        - USE_DEV_REQUIREMENTS=true
    volumes:
      - ./:/app
    command: ["sh", "-c", "python -m flask db upgrade && python -m debugpy --listen 0.0.0.0:5601 -m flask run --no-debugger --host 0.0.0.0 --port 8080"]
    ports:
      - 8080:8080
      - 5696:5601
    environment:
      - FORM_RUNNER_INTERNAL_HOST=http://form-runner-dc:3009
      - FORM_RUNNER_EXTERNAL_HOST=http://localhost:3019
      - DATABASE_URL=postgresql://postgres:password@fab-db-dc:5432/fund_builder   # pragma: allowlist secret
      - FLASK_DEBUG=1
      - FLASK_ENV=development
      - SECRET_KEY=local
    depends_on: [fab-db-dc, form-runner-dc]

  fab-db-dc:
    image: postgres@sha256:fe4efc6901dda0d952306fd962643d8022d7bb773ffe13fe8a21551b9276e50c
    container_name: fab-db-dc
    ports:
      - 5435:5432
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data-fab
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=fund_builder

  form-runner-dc:
    container_name: form-runner-dc
    build:
      context: ../digital-form-builder-adapter
      dockerfile: ./runner/Dockerfile
    ports:
      - "3019:3009"
      - 9238:9228
    command: yarn runner dev
    environment:
      - CHOKIDAR_USEPOLLING=true
      - PREVIEW_MODE=true
      - LAST_COMMIT
      - LAST_TAG
      - JWT_AUTH_ENABLED=false
      - LOG_LEVEL=debug
      - 'NODE_CONFIG={"safelist": ["fab"]}'
      - PREVIEW_MODE=true
      - NODE_ENV=development
      - SINGLE_REDIS=true
      - FORM_RUNNER_ADAPTER_REDIS_INSTANCE_URI=redis://redis-data:6379

  redis-data:
    image: redis@sha256:ea96c435dc17b011f54c6a883c3c45e7726242b075de61c6fe40a10ae6ae0f83
    ports:
      - 6379:6379
