"""simplifying form

Revision ID: 20a58a25f14e
Revises: 80421998c69a
Create Date: 2025-09-16 11:04:30.926147

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "20a58a25f14e"
down_revision = "80421998c69a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("form", schema=None) as batch_op:
        batch_op.add_column(sa.Column("form_name", sa.String(), nullable=False))
        batch_op.drop_column("source_template_id")
        batch_op.drop_column("runner_publish_name")
        batch_op.drop_column("updated_at")
        batch_op.drop_column("form_json")
        batch_op.drop_column("audit_info")
        batch_op.drop_column("name_in_apply_json")
        batch_op.drop_column("created_at")
        batch_op.drop_column("template_name")
        batch_op.drop_column("is_template")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("form", schema=None) as batch_op:
        batch_op.add_column(sa.Column("is_template", sa.BOOLEAN(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column("template_name", sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column("created_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.add_column(
            sa.Column("name_in_apply_json", postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False)
        )
        batch_op.add_column(
            sa.Column("audit_info", postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True)
        )
        batch_op.add_column(
            sa.Column("form_json", postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False)
        )
        batch_op.add_column(sa.Column("updated_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column("runner_publish_name", sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column("source_template_id", sa.UUID(), autoincrement=False, nullable=True))
        batch_op.drop_column("form_name")
    # ### end Alembic commands ###
