"""empty message

Revision ID: 06a42c5b921c
Revises: ca6ccf18956b
Create Date: 2024-10-23 12:06:19.624544

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '06a42c5b921c'
down_revision = 'ca6ccf18956b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('form_section',
    sa.Column('form_section_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('hide_title', sa.Boolean(), nullable=False),
    sa.Column('is_template', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('form_section_id', name=op.f('pk_form_section'))
    )
    with op.batch_alter_table('form', schema=None) as batch_op:
        batch_op.add_column(sa.Column('form_json', postgresql.JSON(none_as_null=True, astext_type=sa.Text()), nullable=True))

    with op.batch_alter_table('page', schema=None) as batch_op:
        batch_op.add_column(sa.Column('form_section_id', sa.UUID(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_page_form_section_id_form_section'), 'form_section', ['form_section_id'], ['form_section_id'])
        batch_op.drop_column('section')

    with op.batch_alter_table('round', schema=None) as batch_op:
        batch_op.alter_column('section_base_path',
               existing_type=sa.INTEGER(),
               server_default=sa.text("nextval('section_base_path_seq')"),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('round', schema=None) as batch_op:
        batch_op.alter_column('section_base_path',
               existing_type=sa.INTEGER(),
               server_default=sa.text("nextval('section_base_path_seq'::regclass)"),
               existing_nullable=True)

    with op.batch_alter_table('page', schema=None) as batch_op:
        batch_op.add_column(sa.Column('section', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_page_form_section_id_form_section'), type_='foreignkey')
        batch_op.drop_column('form_section_id')

    with op.batch_alter_table('form', schema=None) as batch_op:
        batch_op.drop_column('form_json')

    op.drop_table('form_section')
    # ### end Alembic commands ###
