"""Remove name_in_apply_json from form table

Revision ID: 400961897372
Revises: 7a408a985969
Create Date: 2025-09-23 20:21:45.817699

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "400961897372"
down_revision = "7a408a985969"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table("form", schema=None) as batch_op:
        batch_op.drop_column("name_in_apply_json")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table("form", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("name_in_apply_json", postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False)
        )

    # ### end Alembic commands ###
