"""Remove COnditions from components

Revision ID: e553f67592fa
Revises: 9c948b9f4833
Create Date: 2025-07-01 13:09:13.145682

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "e553f67592fa"
down_revision = "9c948b9f4833"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("component", schema=None) as batch_op:
        batch_op.drop_column("conditions")

    with op.batch_alter_table("round", schema=None) as batch_op:
        batch_op.alter_column(
            "section_base_path",
            existing_type=sa.INTEGER(),
            server_default=sa.text("nextval('section_base_path_seq')"),
            existing_nullable=True,
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("round", schema=None) as batch_op:
        batch_op.alter_column(
            "section_base_path",
            existing_type=sa.INTEGER(),
            server_default=sa.text("nextval('section_base_path_seq'::regclass)"),
            existing_nullable=True,
        )

    with op.batch_alter_table("component", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("conditions", postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True)
        )

    # ### end Alembic commands ###
