"""Add status column to round table

Revision ID: 7b151261e00d
Revises: b7274090d05a
Create Date: 2025-03-06 00:29:00.000000

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "7b151261e00d"
down_revision = "b7274090d05a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("round", schema=None) as batch_op:
        batch_op.add_column(sa.Column("status", sa.String(), server_default="In progress", nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("round", schema=None) as batch_op:
        batch_op.drop_column("status")

    # ### end Alembic commands ###
