"""Adds 'send_incomplete_application_emails' property to Round model

Revision ID: e78353152e65
Revises: 600ed3371381
Create Date: 2025-12-15 10:41:27.160358

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "e78353152e65"
down_revision = "600ed3371381"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("round", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "send_incomplete_application_emails", sa.Boolean(), nullable=False, server_default=sa.text("true")
            )
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("round", schema=None) as batch_op:
        batch_op.drop_column("send_incomplete_application_emails")

    # ### end Alembic commands ###
