"""Remove form_json from form table

Revision ID: aeb09e21498b
Revises: 400961897372
Create Date: 2025-09-24 19:10:14.676067

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "aeb09e21498b"
down_revision = "400961897372"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table("form", schema=None) as batch_op:
        batch_op.drop_column("form_json")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table("form", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("form_json", postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False)
        )

    # ### end Alembic commands ###
