"""empty message

Revision ID: 17a167f9bf21
Revises: 600ed3371381
Create Date: 2025-12-11 15:31:56.561969

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "17a167f9bf21"
down_revision = "600ed3371381"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("round", schema=None) as batch_op:
        batch_op.alter_column(
            "section_base_path",
            existing_type=sa.INTEGER(),
            server_default=sa.text("nextval('section_base_path_seq')"),
            existing_nullable=True,
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("round", schema=None) as batch_op:
        batch_op.alter_column(
            "section_base_path",
            existing_type=sa.INTEGER(),
            server_default=sa.text("nextval('section_base_path_seq'::regclass)"),
            existing_nullable=True,
        )

    # ### end Alembic commands ###
