"""remove 'application_reminder_sent' property from Round model

Revision ID: c21727cd35c0
Revises: e78353152e65
Create Date: 2025-12-29 09:28:30.933911

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "c21727cd35c0"
down_revision = "e78353152e65"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("round", schema=None) as batch_op:
        batch_op.drop_column("application_reminder_sent")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("round", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "application_reminder_sent",
                sa.BOOLEAN(),
                autoincrement=False,
                nullable=False,
                server_default=sa.text("false"),
            )
        )

    # ### end Alembic commands ###
