"""Add url_path to form table

Revision ID: 41727a369600
Revises: 80421998c69a
Create Date: 2025-09-23 16:21:15.326248

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "41727a369600"
down_revision = "80421998c69a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table("form", schema=None) as batch_op:
        batch_op.add_column(sa.Column("url_path", sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table("form", schema=None) as batch_op:
        batch_op.drop_column("url_path")

    # ### end Alembic commands ###
