"""Make form_json non-nullable

Revision ID: 0cec5f1e34b8
Revises: e553f67592fa
Create Date: 2025-08-12 18:02:27.716911

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "0cec5f1e34b8"
down_revision = "e553f67592fa"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("form", schema=None) as batch_op:
        batch_op.alter_column("form_json", existing_type=postgresql.JSON(astext_type=sa.Text()), nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("form", schema=None) as batch_op:
        batch_op.alter_column("form_json", existing_type=postgresql.JSON(astext_type=sa.Text()), nullable=True)

    # ### end Alembic commands ###
