"""adding send_deadline_reminder_emails to Round model

Revision ID: 5b361b6e7b57
Revises: c21727cd35c0
Create Date: 2026-01-27 16:22:40.178182

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "5b361b6e7b57"
down_revision = "c21727cd35c0"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("round", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("send_deadline_reminder_emails", sa.Boolean(), nullable=False, server_default=sa.text("true"))
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("round", schema=None) as batch_op:
        batch_op.drop_column("send_deadline_reminder_emails")

    # ### end Alembic commands ###
