"""Remove extraneous fields from form table

Revision ID: 7a408a985969
Revises: 41727a369600
Create Date: 2025-09-23 18:22:22.073668

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "7a408a985969"
down_revision = "41727a369600"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table("form", schema=None) as batch_op:
        batch_op.drop_column("is_template")
        batch_op.drop_column("audit_info")
        batch_op.drop_column("template_name")
        batch_op.drop_column("source_template_id")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table("form", schema=None) as batch_op:
        batch_op.add_column(sa.Column("source_template_id", sa.UUID(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column("template_name", sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(
            sa.Column("audit_info", postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True)
        )
        batch_op.add_column(sa.Column("is_template", sa.BOOLEAN(), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
