"""Add MultiInputField to ComponentType Enum and columns children and schema to Component. Add column options to Page

Revision ID: da30746cec39
Revises: ca61d3b746f6
Create Date: 2024-10-16 13:47:16.968837

"""
from alembic import op
import sqlalchemy as sa

from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'da30746cec39'
down_revision = 'ca61d3b746f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
        
    op.execute("ALTER TYPE componenttype ADD VALUE 'MULTI_INPUT_FIELD';")
    with op.batch_alter_table('component', schema=None) as batch_op:
        batch_op.add_column(sa.Column('children', postgresql.JSON(none_as_null=True, astext_type=sa.Text()), nullable=True))
        batch_op.add_column(sa.Column('schema', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    with op.batch_alter_table('page', schema=None) as batch_op:
        batch_op.add_column(sa.Column('options', postgresql.JSON(none_as_null=True, astext_type=sa.Text()), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('component', schema=None) as batch_op:
        batch_op.drop_column('children')
        batch_op.drop_column('schema')
    with op.batch_alter_table('page', schema=None) as batch_op:
        batch_op.drop_column('options')
    # ### end Alembic commands ###
