name: Run e2e tests
on:
  workflow_call:
    inputs:
      environment:
        description: "E2E Env Selector"
        type: string
        default: dev
  workflow_dispatch:
    inputs:
      environment:
        description: "E2E Env Selector"
        type: choice
        options:
          - dev
          - test
        default: dev

jobs:
  run_tests:
    name: e2e tests
    permissions:
      id-token: write # This is required for requesting the JWT
      contents: read  # This is required for actions/checkout
    runs-on: ubuntu-latest
    container: mcr.microsoft.com/playwright:v1.47.0-noble
    environment: ${{ inputs.environment }}
    steps:
      - name: Checkout e2e tests
        uses: actions/checkout@v4
      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
      - name: Get current date
        shell: bash
        id: currentdatetime
        run: echo "datetime=$(date +'%Y%m%d%H%M%S')" >> $GITHUB_OUTPUT
      - name: Configure aws credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT }}:role/GithubCopilotDeploy
          role-session-name: COPILOT_${{ inputs.environment }}_FAB_${{ steps.currentdatetime.outputs.datetime }}
          aws-region: eu-west-2
      - name: Run tests
        run: uv run --frozen pytest --e2e --e2e-env ${{ inputs.environment }}
        env:
          E2E_DEVTEST_BASIC_AUTH_USERNAME: ${{ secrets.E2E_DEVTEST_BASIC_AUTH_USERNAME }}
          E2E_DEVTEST_BASIC_AUTH_PASSWORD: ${{ secrets.E2E_DEVTEST_BASIC_AUTH_PASSWORD }}
